/* main.c */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* --- External declarations from the parser (sql_converter.y) --- */

// Declare the main parsing function generated by Bison/Yacc
extern int yyparse(void);

// Declare functions/variables defined in sql_converter.y
extern const char* get_sql_query();
extern void reset_query_status();
extern int is_query_ready();

// Declare functions needed from the lexer (sql_converter.l / lex.yy.c)
struct yy_buffer_state; // Forward declare opaque type
typedef struct yy_buffer_state *YY_BUFFER_STATE;
extern YY_BUFFER_STATE yy_scan_string(const char * str);
extern void yy_delete_buffer(YY_BUFFER_STATE);
extern void yylex_destroy(void); // Good practice to call this at the end

/* --- Main Program --- */

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s \"<English sentence>\"\n", argv[0]);
        fprintf(stderr, "Example: %s \"Please show me the student whose name is \\\"Alice\\\".\"\n", argv[0]);
        return EXIT_FAILURE;
    }

    const char *input_sentence = argv[1];

    // Reset state before parsing
    reset_query_status();

    // Set up the input buffer for Flex to scan the string
    YY_BUFFER_STATE buffer = yy_scan_string(input_sentence);
    if (!buffer) {
         fprintf(stderr, "Error: Could not create buffer for input string.\n");
         return EXIT_FAILURE;
    }

    // Parse the input string
    int parse_result = yyparse(); // This will call yylex() implicitly

    // Clean up the Flex buffer
    yy_delete_buffer(buffer);

    // Clean up lexer state
    yylex_destroy();


    // Check the result
    if (parse_result == 0) { // 0 usually means success for yyparse
        if (is_query_ready()) {
            printf("%s\n", get_sql_query());
            return EXIT_SUCCESS;
        } else {
            // This case might happen if the grammar accepts input but doesn't hit a rule
            // that sets query_ready (e.g., only parsed "Please show me" without a DOT)
            // However, our grammar requires a DOT for the top 'statement' rule.
            // The yyerror function likely caught syntax errors already.
            fprintf(stderr, "Error: Parsing seemed successful, but no SQL query was generated.\n");
            return EXIT_FAILURE;
        }
    } else {
        // yyerror() should have already printed a message
        fprintf(stderr, "Error: Failed to parse the sentence.\n");
        return EXIT_FAILURE; // Indicate failure
    }
}